replicaCount: {{ service.kafka.replication }}

image:
  repository: {{ harbor_url }}/kafka/kafka
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext: {}

service:
  type: NodePort
  port: {{ service.kafka.port }}

resources:
  requests:
    cpu: "{{ k8s_kafka.resources.requests.cpu }}"
    memory: "{{ k8s_kafka.resources.requests.memory }}"
  limits:
    cpu: "{{ k8s_kafka.resources.limits.cpu }}"
    memory: "{{ k8s_kafka.resources.limits.memory }}"


livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  probeCommandTimeout: 2

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  probeCommandTimeout: 2