---
- name: Template kube-admin scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    mode: 0755
  with_items:
    - { src: create_kube_admin.sh.j2, dest: "{{ k8s_master_path }}/create_kube_admin.sh"}

- name: execute scripts and daemon-reload
  shell: |
    cd "{{ k8s_master_path }}"
    /bin/bash ./create_kube_admin.sh

- name: Check k8s master service
  shell: |
    {{ k8s_master_bin_path }}/kubectl get cs
  register: k8s_master_service_status
  run_once: true
  delegate_to: "{{ groups['k8s_master'][0] }}"

- name: check k8s master service status
  debug:
    msg: "{{ k8s_master_service_status }}"
  run_once: true
  delegate_to: "{{ groups['k8s_master'][0] }}"