---
- name: Create kube-scheduler logs dir
  file:
    path: "{{ item }}"
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ k8s_master_logs_path }}/kube-scheduler"

- name: Template kube-scheduler conf and scripts
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    mode: 0755
  with_items:
    - { src: kube-scheduler.conf.j2, dest: "{{ k8s_master_cfg_path }}/kube-scheduler.conf"}
    - { src: kube-scheduler.service.j2, dest: /usr/lib/systemd/system/kube-scheduler.service }
    - { src: create_kube_scheduler.kubeconfig.sh.j2, dest: "{{ k8s_master_path }}/create_kube_scheduler.kubeconfig.sh"}

- name: execute scripts and daemon-reload
  shell: |
    cd "{{ k8s_master_path }}"
    /bin/bash ./create_kube_scheduler.kubeconfig.sh
    systemctl daemon-reload
  notify:
    - Restart kube-scheduler service

- meta: flush_handlers

- name: Check kube-scheduler ports
  wait_for:
    port: "{{ scheduler_port }}"
    state: started
    host: "{{ ansible_host }}"
    delay: 5
    timeout: 60
    connect_timeout: 10
