apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.name" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
