apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticsearch.name" . }}-secret
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
type: Opaque
data:
  elasticsearch-username: {{ .Values.elasticsearch.username | b64enc }}
  elasticsearch-password: {{ .Values.elasticsearch.password | b64enc }}
