image:
  repository: devops.wangtianci.com/open/filebeat
  pullPolicy: Always
  tag: "v7.8.0"

resources:
   limits:
     cpu: "1"
     memory: 1024Mi
   requests:
     cpu: "1"
     memory: 1024Mi

elasticsearch:
  user: elastic
  password: g8UiNqgnfwqW

dataSavePath:
  localLogPath: /opt/app/kubernetes/docker/containers
  containerLogPath: /var/lib/docker/containers
  systemLogPath: /var/log
  containerSystemLogPath: /var/log
  localDataPath: /opt/app/filebeat/data
  containerDataPath: /opt/app/filebeat/data
  type: DirectoryOrCreate

startPolicy:
  enabled: false
  command:
    - sleep
  args:
    - infinity

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
