apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Release.Name }}-{{ .Values.global.namespace.prefix }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics-port
      protocol: TCP
      name: kube-state-metrics
      nodePort: null
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
