apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  namespace: {{ template "zookeeper.namespace" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-client
      port: {{ .Values.zk_services.ClientPort }}
    - name: follower
      port: {{ .Values.zk_services.FollowerContainerPort }}
    - name: tcp-election
      port: {{ .Values.zk_services.ElectionContainerPort }}
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}