---
- name: create haproxy config dir
  file:
    path: "{{ haproxy_cfg_path }}"
    state: directory

- name: upload haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_cfg_path }}/haproxy.cfg"

- name: docker login
  shell: |
    docker login {{ DockerRegistry }} -u{{ harbor_user }} -p{{ harbor_pass }}

- name: start haproxy  container
  shell: |
    docker run -d \
      --name haproxy \
      --network host \
      --restart always \
      -v {{ haproxy_cfg_path }}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg \
      {{ DockerRegistry }}/base/{{ haproxy_repository.split("/")[1] }}

