global:
  resolve_timeout: 5m

templates:
  - "{{ servie.containerPath }}/{{ role_name }}/templates/wechat.tmpl" // 告警内容模板

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: wechat

receivers:
  - name: 'wechat'
    wechat_configs:
    - corp_id: '{{ wechat_corp_id }}'
      agent_id: '{{ wechat_agent_id }}'
      api_secret: '{{ wechat_api_secret }}'
      to_user: '{{ wechat_to_user }},{{ wechat_to_tag }},{{ wechat_to_user }}'
      send_resolved: {{ service.alertmanager.sendResolved }}