global:
  resolve_timeout: 5m

templates:
  - "{{ service.containerPath }}/{{ role_name }}/templates/wechat.tmpl"

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: wechat

receivers:
  - name: 'wechat'
    wechat_configs:
    - corp_id: '{{ wechat_corp_id }}'
      agent_id: '{{ wechat_agent_id }}'
      api_secret: '{{ wechat_api_secret }}'
      to_user: '{{ wechat_to_user }},{{ wechat_to_tag }},{{ wechat_to_party }}'
      api_url: 'http://39.105.101.140:9000/alarm'
      send_resolved: {{ service.alertmanager.sendResolved }}