apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-exporter.fullname" . }}
  labels:
    {{- include "node-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "node-exporter.selectorLabels" . | nindent 4 }}
