# 操作系统基础镜像
FROM centos:centos7.9.2009

# 打包的人
MAINTAINER "wangtianci"

# 基础路径
RUN mkdir -pvm 755 /opt/workspace \
    /root/.cargo

# 依赖源
COPY ali-centos.repo /etc/yum.repos.d/
COPY ali-epel.repo /etc/yum.repos.d/
COPY config /root/.cargo/

# WORKDIR
ADD rust-1.61.0-x86_64-unknown-linux-gnu.tar.gz /opt/workspace
WORKDIR /opt/workspace/rust-1.61.0-x86_64-unknown-linux-gnu

# 安装rust环境
RUN yum install gcc* openssl openssl-devel git libpcap libpcap-devel -y \
    && sh install.sh

# 时间同步
RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

# 设置编码
ENV LC_ALL=zh_CN.utf8
ENV LANG=zh_CN.utf8
ENV LANGUAGE=zh_CN.utf8
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8


# 启动容器执行的命令，仅用于验证安装配置是否正确，生产环境使用需注释后再build
# CMD ["sleep", "3600"]