---
- name: add kube-apiserver
  supervisorctl:
    name:kube-apiserver
    state: present

- name: restart kube-apiserver
  supervisorctl:
    name: kube-apiserver
    state: restarted

- name: Restart kube-controller-manager service
  systemd:
    name: kube-controller-manager
    enabled: true
    state: restarted
    daemon_reload: yes

- name: Restart kube-scheduler service
  systemd:
    name: kube-scheduler
    enabled: true
    state: restarted
    daemon_reload: yes