---
- name: add kube-apiserver
  supervisorctl:
    name: kube-apiserver
    state: present

- name: restart kube-apiserver
  supervisorctl:
    name: kube-apiserver
    state: restarted

- name: add kube-controller-manager
  supervisorctl:
    name: kube-controller-manager
    state: present

- name: restart kube-controller-manager
  supervisorctl:
    name: kube-controller-manager
    state: restarted

- name: add kube-scheduler
  supervisorctl:
    name: kube-scheduler
    state: present

- name: restart kube-scheduler
  supervisorctl:
    name: kube-scheduler
    state: restarted