apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: td-ecm-data-commodity-operation-server-test
  labels:
    k8s-app: td-ecm-data-commodity-operation-server-test
    qcloud-app: td-ecm-data-commodity-operation-server-test
  name: td-ecm-data-commodity-operation-server-test
  namespace: test
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: td-ecm-data-commodity-operation-server-test
      qcloud-app: td-ecm-data-commodity-operation-server-test
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: td-ecm-data-commodity-operation-server-test
        qcloud-app: td-ecm-data-commodity-operation-server-test
        monitor: jmx-java
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: k8s-app
                      operator: In
                      values:
                        - td-ecm-data-commodity-operation-server-test
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: PATH
              value: /usr/local/jdk1.8.0_271/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: JAVA_HOME
              value: /usr/local/jdk1.8.0_271/
            - name: APP_HOME
              value: /
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -Dspring.profiles.active=test -Djava.security.egd=file:/dev/./urandom -Xms187M -Xmx1503M -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -Xloggc:/data/app/logs/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3 -XX:GCLogFileSize=100m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/app/logs/oom.hprof -XX:ErrorFile=/data/app/logs/hs_err_%p.log -javaagent:/usr/local/agents/skywalking/skywalking-agent.jar -DSW_AGENT_NAME=td-ecm-data-commodity-operation-server-test -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap.teddymobile.net:11800 -javaagent:/usr/local/agents/prometheus/jmx_prometheus_javaagent-0.14.0.jar=9091:/usr/local/agents/prometheus/jmx_exporter.yml
          image: harbor-test-jd.teddymobile.net/teddy_repo/td-operation-server-test:202109131448.2119befd
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 30
          name: td-ecm-data-commodity-operation-server-test
          ports:
            - containerPort: 9091
              name: jmx
              protocol: TCP
            - containerPort: 9090
              name: java
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/app/logs
              name: data
              subPathExpr: $(POD_NAME)/
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: jd-123456
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /data/app/logs
            type: DirectoryOrCreate
          name: data