apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
        encoding: utf-8
        tail_files: true
        paths:
          - /var/lib/docker/containers/*/v1.k2.*.log
    output.kafka:
      codec.format:
        string: '%{[@timestamp]} %{[host.name]} %{[log.file.path]} %{[message]}'
      enabled: true
      hosts: ["10.20.5.16:9092"]
      topic: '%{[fields.log_topic]}'
      worker: 4
      version: '0.10.1'
      partition.round_robin:
        reachable_only: true
      required_acks: 1
      compression: lz4
      max_message_bytes: 104857600
      keep_alive: 60s
      broker_timeout: 30s
      retry.max: 3
      retry.backoff: 1s
    processors:
      - script:
          lang: javascript
          id: file_regex_filter
          source: >
            var v1 = new RegExp("v[1-9]\.(k[0-9])\.a[0-9]{1,10}\.([a-zA-Z0-9_-]+)\.[0-9]{10}.*[\.]{0,1}log$");
            function process(event) {
                var mt = event.Get("log.file.path").match(v1);
                if (mt !== null && mt.length >= 1) {
                    if (mt[1] === "k0") {
                        event.Cancel();
                        return;
                    }
                    event.Put("fields.log_topic", mt[2]);
                } else {
                  event.Cancel();
                  return;
                }
            }
    logging.level: error
    logging.to_stderr: true
    http.enabled: true
    http.port: 5266
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-13T07:16:20Z"
  labels:
    k8s-app: td-ba-filebeat-k2
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:filebeat.yml: {}
      f:metadata:
        f:labels:
          .: {}
          f:k8s-app: {}
    manager: tke-apiserver
    operation: Update
    time: "2021-04-13T07:16:20Z"
  name: td-ba-filebeat-config-k2
  namespace: devops
  resourceVersion: "1968981813"
  selfLink: /api/v1/namespaces/devops/configmaps/td-ba-filebeat-config-k2
  uid: e4160e11-8979-4971-b4ee-3c42541df624