# 操作系统基础镜像
FROM centos:centos7.9.2009
# 打包的人
MAINTAINER "devops@teddymobile.cn"

# 运行
RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && yum install epel-release -y \
    && rpm -v --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro \
    && rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm \
    && yum install -y wget vim net-tools unzip zip ffmpeg ffmpeg-devel \
    && mkdir /usr/local/agents \
    && wget http://wget.teddymobile.net/jdk-8u271-linux-x64.tar.gz \
    && tar xf jdk-8u271-linux-x64.tar.gz && mv jdk1.8.0_271 /usr/local/ \
    && wget http://wget.teddymobile.net/skywalking/skywalking-agent.tar.gz \
    && tar xf skywalking-agent.tar.gz && mv skywalking /usr/local/agents/ \
    && wget http://wget.teddymobile.net/prometheus-agent.tar.gz \
    && tar xf prometheus-agent.tar.gz && mv prometheus /usr/local/agents/ \
    && rm -rf prometheus-agent.tar.gz jdk-8u271-linux-x64.tar.gz skywalking-agent.tar.gz


# 定义环境变量
ENV JAVA_HOME /usr/local/jdk1.8.0_271/
ENV PATH $JAVA_HOME/bin:$PATH

# 设置编码
ENV LC_ALL=zh_CN.utf8
ENV LANG=zh_CN.utf8
ENV LANGUAGE=zh_CN.utf8
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8

# 启动容器执行的命令，仅用于验证安装配置是否正确，生产环境使用需注释后再build
#CMD ["java","-version"]
