apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.name" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "ClusterIP" }}
  type: {{ .Values.service.type }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - name: {{ include "kube-state-metrics.name" . }}
      port: {{ .Values.service.extraArgs.port }}
      targetPort: {{ .Values.service.extraArgs.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.extraArgs.port }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
