{{- if .Values.externalAccess.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-external
  namespace: {{ template "kafka.namespace" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.externalAccess.type }}
  externalName: {{ .Release.Name }}-zookeeper-headless.{{ .Release.Name }}-zookeeper.svc.cluster.local
  ports:
    - name: tcp-client
      port: {{ .Values.kafka_services.ClientPort }}
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
{{ end }}