apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  namespace: {{ template "kafka.namespace" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: tcp-client
      port: {{ .Values.kafka_services.ClientPort }}
      protocol: TCP
    - name: tcp-internal
      port: {{ .Values.kafka_services.InternalPort }}
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}