FROM harbor.in.starcross.cn/base/centos:centos7.9.2009

RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && mkdir /opt/workspace

ADD grafana-9.1.7.tar.gz /opt/workspace

WORKDIR /opt/workspace/grafana

ENTRYPOINT ["./bin/grafana-server"]