apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Name }}-{{ .Values.global.namespace.prefix }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Name }}-{{ .Values.global.namespace.prefix }}
    name: {{ include "prometheus.serviceAccountName" . }}