---
- name: Create keepalived config dir
  file:
    path: "{{ keepalived_cfg_path }}"
    state: directory
    mode: 0755

- name: template keepalived.cfg
  template:
    src: keepalived.cfg.j2
    dest: "{{ keepalived_cfg_path }}/keepalived.cfg"
    mode: 0755

- name: start keepalived
  shell: |
    docker run -itd \
        --privileged=true \
        --name keepalived \
        --network host \
        --restart always \
        -v {{ haproxy_cfg_path }}/keepalived.cfg:/etc/keepalived/keepalived.cfg \
        {{ DockerRegistry }}/base/base/keepalived:{{ keepalived_repository.split(":")[1] }}
