---
- name: Create keepalived config dir
  file:
    path: "{{ keepalived_cfg_path }}"
    state: directory
    mode: 0755

- name: template keepalived.cfg
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_cfg_path }}/keepalived.conf"
    mode: 0644

- name: start keepalived
  shell: |
    docker stop keepalived
    docker rm keepalived
    docker run -d \
        --privileged=true \
        --name keepalived \
        --network host \
        --restart always \
        -v {{ keepalived_cfg_path }}/keepalived.conf:/etc/keepalived/keepalived.conf \
        {{ DockerRegistry }}/base/keepalived:{{ keepalived_repository.split(":")[1] }}
