replicaCount: 1

image:
  repository: devops.wangtianci.com/base/prometheus
  pullPolicy: Always
  tag: "2.28.1"

service:
  type: NodePort
  port: 39090
  basePath: /opt/workspace/prometheus
  extraArgs:
    storage.tsdb.retention.time: 15d
    storage.tsdb.path: /opt/workspace/prometheus/data
    config.file: /etc/prometheus.yml
    web.enable-lifecycle:
    web.enable-admin-api:

livenessProbe:
  enabled: true
  path: /-/healthy
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 120
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /-/ready
  initialDelaySeconds: 0
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 120
  successThreshold: 1

resources:
   limits:
     cpu: 1
     memory: 1024Mi
   requests:
     cpu: 1
     memory: 1024Mi

serviceAccount:
 create: true
