---
- name: stop firewalld service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
     - firewalld
     - NetworkManager

- name: stop selinux
  selinux:
    state: disabled

- name: stop selinux at once
  shell: setenforce 0
  ignore_errors: True

