apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.name" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      nodePort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
