# 操作系统基础镜像
FROM devops.wangtianci.com/module/node-base:v16.14.2

# 打包的人
MAINTAINER "wangtianci"

ARG PROJECT_NAME

ENV service_name=${PROJECT_NAME}

COPY $service_name /opt/workspace/$service_name

WORKDIR /opt/workspace/$service_name

RUN yarn \
    && yarn build

# 测试镜像使用，在生产环境中需注释
CMD ["sleep","3600"]