global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
         - alertmanager.tianciwang:39093

rule_files:
  - "/etc/rules.yml"

scrape_configs:
  - job_name: node-exporter
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_name
      action: keep
      regex: node-exporter-(.+)
    - source_labels:
      - __meta_kubernetes_namespace
      action: replace
      target_label: kubernetes_namespace
    - source_labels:
      - __meta_kubernetes_pod_name
      action: replace
      target_label: pod_name
    - source_labels:
      - __meta_kubernetes_pod_phase
      action: replace
      target_label: pod_status
    - source_labels:
      - __meta_kubernetes_pod_host_ip
      action: replace
      target_label: host_machine
  - job_name: alertmanager
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_name
      action: keep
      regex: alertmanager-(.+)
    - source_labels:
      - __meta_kubernetes_namespace
      action: replace
      target_label: kubernetes_namespace
    - source_labels:
      - __meta_kubernetes_pod_name
      action: replace
      target_label: pod_name
    - source_labels:
      - __meta_kubernetes_pod_phase
      action: replace
      target_label: pod_status
    - source_labels:
      - __meta_kubernetes_pod_host_ip
      action: replace
      target_label: host_machine
