groups:
- name: "alert-environment"
  rules:
  - alert: instance_memory_use
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
    for: 1m
    labels:
      alertname: 服务器内存状态
      serverity: 紧急
    annotations:
      summary: "内存告警"
      description: "{{ $labels.host_machine }} 可用内存 {{$value | printf \"%.2f\" }}% < 20%"

  - alert: instance_load5
    expr: node_load5 > 30
    for: 1m
    labels:
      alertname: 服务器负载
      serverity: 轻微
    annotations:
      summary: "服务器负载告警"
      description: "{{ $labels.host_machine }} 服务器近1min负载为{{$value | printf \"%.2f\" }}%,已超过30%"