---
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - fortress_Build
  - fortress_Make_Tar

fortress_build:
  stage: fortress_Build
  script:
    - cargo build --release
  artifacts:
    expire_in: 10 mins
    paths:
      - target/release/$CI_PROJECT_NAME
  only:
    - /^[a-zA-Z].*/(develop|bugfix|hotfix)/.*$/
    - master

fortress_tarfile:
  stage: fortress_Make_Tar
  needs:
    - [fortress_build]
  before_script:
    - if [ ! -d "$CI_BUILDS_DIR/Packages/$CI_PROJECT_NAME" ];then
    - mkdir -pvm 755 $CI_BUILDS_DIR/Packages/$CI_PROJECT_NAME
    - fi
  script:
    - if [ -f ./target/release/$CI_PROJECT_NAME ];then
    - echo "$CI_COMMIT_SHA" &>> ./target/release/ci_commit_sha_id
    - tar -zcf "$CI_PROJECT_NAME"_"$CI_COMMIT_SHA".tar.gz target/release/$CI_PROJECT_NAME ./target/release/ci_commit_sha_id
    - if [ $? -eq 0 ];then
    - mv "$CI_PROJECT_NAME"_"$CI_COMMIT_SHA".tar.gz $CI_BUILDS_DIR/Packages/$CI_PROJECT_NAME
    - if [ $? -eq 0 ];then
    - echo "`date +%Y-%m-%d" "%H:%M:%S` $CI_COMMIT_REF_NAME  "$CI_PROJECT_NAME"_"$CI_COMMIT_SHA".tar.gz 拷贝$CI_BUILDS_DIR/Packages/$CI_PROJECT_NAME成功"
    - else
    - echo "`date +%Y-%m-%d" "%H:%M:%S` $CI_COMMIT_REF_NAME  "$CI_PROJECT_NAME"_"$CI_COMMIT_SHA".tar.gz 拷贝$CI_BUILDS_DIR/Packages/$CI_PROJECT_NAME失败"
    - exit
    - fi
    - else
    - echo "`date +%Y-%m-%d" "%H:%M:%S` $CI_COMMIT_REF_NAME "$CI_PROJECT_NAME"_"$CI_COMMIT_SHA".tar.gz 打包失败"
    - exit
    - fi
    - else
    - echo "`date +%Y-%m-%d" "%H:%M:%S` $CI_COMMIT_REF_NAME $CI_COMMIT_SHA 编译失败"
    - exit
    - fi
  dependencies:
    - fortress_build
  only:
    - /^[a-zA-Z].*/(develop|bugfix|hotfix)/.*$/
    - master
