apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager.name" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alertmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "alertmanager.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "alertmanager.serviceAccountName" . }}
      containers:
        - name: {{ include "alertmanager.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: alertmanager
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            tcpSocket:
              port: alertmanager
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            tcpSocket:
              port: alertmanager
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: {{ .Values.service.basePath }}/data
            - name: logdir
              mountPath: {{ .Values.service.basePath }}/log
            - name: config
              mountPath: /etc/alertmanager.yml
              subPath: alertmanager.yml
            - name: alert-template
              mountPath: {{ .Values.service.basePath }}/templates/wechat.tmpl
              subPath: wechat.tmpl
      volumes:
        - name: datadir
          hostPath:
            path: {{ .Values.service.basePath }}/data
            type: DirectoryOrCreate
        - name: logdir
          hostPath:
            path: {{ .Values.service.basePath }}/logs
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: {{ include "alertmanager.name" . }}
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
        - name: alert-template
          configMap:
            name: {{ include "alertmanager.name" . }}
            items:
              - key: wechat.yml
                path: wechat.tmpl

