apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.name" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "ClusterIP" }}
  type: {{ .Values.service.type }}
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - name: alertmanager
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end }}
      protocol: TCP

  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}
