apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.name" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      containers:
        - name: {{ include "grafana.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range $key, $value := .Values.service.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
            {{- end }}
          ports:
            - name: grafana
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            tcpSocket:
              port: grafana
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            tcpSocket:
              port: grafana
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: {{ .Values.service.basePath }}/data
            - name: logdir
              mountPath: {{ .Values.service.basePath }}/log
            - name: config
              mountPath: {{ .Values.service.basePath }}/conf/grafana.ini
              subPath: grafana.ini
            - name: prometheus-datasource
              mountPath: {{ .Values.service.basePath }}/conf/provisioning/datasources/prometheus.yaml
              subPath: prometheus.yaml
            - name: node-exporter-dashboard
              mountPath: {{ .Values.service.basePath }}/conf/provisioning/dashboards/node-exporter.json
              subPath: node-exporter.json
            - name: main-dashboard
              mountPath: {{ .Values.service.basePath }}/conf/provisioning/dashboards/sample.yaml
              subPath: sample.yaml
      volumes:
        - name: datadir
          hostPath:
            path: {{ .Values.service.basePath }}/data
            type: DirectoryOrCreate
        - name: logdir
          hostPath:
            path: {{ .Values.service.basePath }}/logs
            type: DirectoryOrCreate
        - name: config
          configMap:
            name: {{ include "grafana.name" . }}
            items:
              - key: grafana.ini
                path: grafana.ini
        - name: prometheus-datasource
          configMap:
            name: {{ include "grafana.name" . }}
            items:
              - key: dashboard.yaml
                path: prometheus.yaml
        - name: node-exporter-dashboard
          configMap:
            name: {{ include "grafana.name" . }}
            items:
              - key: node.json
                path: node-exporter.json
        - name: main-dashboard
          configMap:
            name: {{ include "grafana.name" . }}
            items:
              - key: sample.yaml
                path: sample.yaml