ARG openjdk
ARG harborUrl

# image source
FROM ${harborUrl}/base/openjdk:${openjdk}

ARG tag
ARG name

RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && mkdir /opt/workspace  
    
ADD ${name}-${tag}.tar.gz /opt/workspace/
WORKDIR /opt/workspace/${name}
RUN useradd es \
    && chown -R es:es /opt
USER es
CMD ["bin/elasticsearch"] 
