service:
  containerPath: /opt/workspace
  prometheus:
    replication: 1
    pullPolicy: Always
    tag: 2.28.1
    port: 39090
    nodePort: True
    requests:
      cpu: "1024"
      memory: "1024Mi"
    limits:
      cpu: "2048"
      memory: "2048Mi"
    checkHealthy: true
    dbRetention: 15d
