service:
  containerPath: /opt/workspace
  prometheus:
    replication: 1
    pullPolicy: Always
    tag: 2.28.1
    port: 9090
    nodePort: True
    limits:
      cpu: 1024Mi
      memory: 1024Mi
    requests:
      cpu: 2048Mi
      memory: 2048Mi
    checkHealthy: true
    dbRetention: 15d
