service:
  containerPath: /opt/workspace
  prometheus:
    replication: 1
    pullPolicy: Always
    tag: 2.28.1
    port: 39090
    nodePort: True
    requests:
      cpu: "1024m"
      memory: "1024Mi"
    limits:
      cpu: "1024m"
      memory: "1024Mi"
    checkHealthy: true
    dbRetention: 15d
  alertmanager:
    replication: 1
    pullPolicy: Always
    tag: 0.23.0
    port: 39093
    nodePort: False
    requests:
      cpu: "1024m"
      memory: "1024Mi"
    limits:
      cpu: "1024m"
      memory: "1024Mi"
    checkHealthy: true
    dataRetention: 168h
    sendResolved: true
  grafana:
    replication: 1
    pullPolicy: Always
    tag: 9.1.7
    port: 30000
    nodePort: True
    requests:
      cpu: "1024m"
      memory: "1024Mi"
    limits:
      cpu: "1024m"
      memory: "1024Mi"
    checkHealthy: true