ARG centos
ARG harborUrl

FROM ${harborUrl}/base/centos:${centos}

ARG tag
ARG name

RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && mkdir -pvm 755 /opt/workspace
    
ADD ${name}-${tag}.tar.gz /opt/workspace/

WORKDIR /opt/workspace/${name}

ENTRYPOINT ["./node_exporter"]