---
- name: Tempalte k8s node cmd to system
  template:
    src: k8s-node.sh.j2
    dest: /etc/profile.d/k8s-node.sh
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    mode: 0755

- name: Copy docker.json to kubelet dir
  shell: |
    cp $HOME/.docker/config.json /var/lib/kubelet/
  with_items:
    - "{{ groups['k8s_node'] }}"
  ignore_errors: True

- name: source /etc/profile
  shell: |
    source /etc/profile.d/k8s-node.sh
    sleep 30
