---
- name: k8s master approve node
  shell: |
    kubectl certificate approve `kubectl get csr | grep Pending | awk '{print $1}'`
  ignore_errors: True

- name: k8s master add label
  shell: |
    kubectl label node {{ hostvars[host]['ansible_host'] }} node-role.kubernetes.io/master=master
  with_items:
    - "{{ groups['k8s_master'] }}"
  loop_control:
    loop_var: host
  ignore_errors: True

- name: k8s node add label
  shell: |
    kubectl label node {{ hostvars[host]['ansible_host'] }} node-role.kubernetes.io/node=node
  with_items:
    - "{{ groups['k8s_node'][3:] }}"
  loop_control:
    loop_var: host
  ignore_errors: True

- name: Check k8s cluster status
  shell: |
    kubectl get nodes
  register: result

- debug:
    msg: "{{ result.stdout_lines }}"
