---
- import_tasks: prepare.yml
  tags: K8sPrepare
- import_tasks: cni.yml
  tags: cni
- import_tasks: kubelet.yml
  tags: kubelet
- import_tasks: kube-proxy.yml
  tags: kube-proxy
  when: inventory_hostname in groups['k8s_node'][{{ groups.k8s_master | length }}:]
- import_tasks: global_cmd.yml
  tags: global_cmd
  when: inventory_hostname in groups['k8s_node'][{{ groups.k8s_master | length }}:]
- import_tasks: k8s-cluster.yml
  tags: k8s-cluster
  when: inventory_hostname in groups['k8s_master'][0]