apiVersion: 1
providers:
- name: 'default'
  orgId: 1
  folder: ''
  folderUid: ''
  type: file
  options:
    path: {{ service.containerPath }}/{{ role_name }}/conf/provisioning/dashboards/
  allowUiUpdates: true