apiVersion: 1
providers:
- name: 'default'
  orgId: 1
  folder: ''
  folderUid: ''
  type: file
  options:
    path: {{ .Values.service.basePath }}/conf/provisioning/dashboards/
  allowUiUpdates: true