# version && harbor url
ARG tag
ARG url
ARG name

# image source
FROM ${url}/base/${name}:${tag}

# MAINTAINER
MAINTAINER "starcross"

# sync time
RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

# data save path
RUN mkdir -pvm 755 /data/mysql/data \
    && mkdir -pvm 755 /data/mysql/tmpdata \
    && chown -R mysql.mysql /data/

# CMD ["sleep", "3600"]