replicaCount: 1

image:
  repository: devops.wangtianci.com/open/node_exporter
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

resources:
   limits:
     cpu: "1"
     memory: 1024Mi
   requests:
     cpu: "1"
     memory: 1024Mi

node_exporter:
  ClientPort: 9100
  extraArgs:
    path.procfs: /host/proc
    path.sysfs: /host/sys
    path.rootfs: /host/root
    collector.filesystem.ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
  hostNetwork: true
  hostPID: true
  hostIPC: true

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

startPolicy:
  enabled: false
  command:
    - sleep
  args:
    - infinity

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}