---
- name: add kubelet
  supervisorctl:
    name: kubelet
    state: present

- name: restart kubelet
  supervisorctl:
    name: kubelet
    state: restarted

- name: add kube-proxy
  supervisorctl:
    name: kube-proxy
    state: present

- name: restart kube-proxy
  supervisorctl:
    name: kube-proxy
    state: restarted
