FROM harbor.in.starcross.cn/base/centos:centos7.9.2009

RUN rm -f /etc/localtime \
    && ln -sv /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && mkdir /opt/workspace

ADD prometheus-2.28.1.tar.gz /opt/workspace

WORKDIR /opt/workspace/prometheus

ENTRYPOINT ["./prometheus"]