---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "filebeat.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "filebeat.serviceAccountName" . }}
  namespace: {{ template "filebeat.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "filebeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io