apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "filebeat.fullname" . }}
  namespace: {{ template "filebeat.namespace" . }}
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "filebeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "filebeat.selectorLabels" . | nindent 8 }}
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      serviceAccountName: {{ include "filebeat.serviceAccountName" . }}
      containers:
        - name: {{ template "filebeat.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.startPolicy.enabled }}
          command: {{- toYaml .Values.startPolicy.command | nindent 12 }}
          args: {{- toYaml .Values.startPolicy.args | nindent 12 }}
          {{- else }}
          args: [
            "-c","/etc/filebeat.yml"
          ]
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              subPath: filebeat-config
            - name: system-log
              mountPath: {{ .Values.dataSavePath.containerSystemLogPath }}
            - name: container-log
              mountPath: {{ .Values.dataSavePath.containerLogPath }}
            - name: filebeat-datadir
              mountPath: {{ .Values.dataSavePath.containerDataPath }}
            - name: filebeat-logdir
              mountPath: {{ .Values.dataSavePath.serviceContainerLogPath }}
      dnsPolicy: ClusterFirst
      volumes:
        - name: filebeat-config
          configMap:
            name: {{ template "filebeat.configname" . }}
        - name: system-log
          hostPath:
            path: {{ .Values.dataSavePath.systemLogPath }}
            type: {{ .Values.dataSavePath.type }}
        - name: container-log
          hostPath:
             path: {{ .Values.dataSavePath.localLogPath }}
             type: {{ .Values.dataSavePath.type }}
        - name: filebeat-datadir
          hostPath:
            path: {{ .Values.dataSavePath.localDataPath }}
            type: {{ .Values.dataSavePath.type }}
        - name: filebeat-logdir
          hostPath:
            path: {{ .Values.dataSavePath.serviceLocalLogPath }}
            type: {{ .Values.dataSavePath.type }}