{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "filebeat.serviceAccountName" . }}
  namespace: kube-system
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
{{- end }}
